const axios = require('axios');

const HUGGINGFACE_API_URL = 'https://api-inference.huggingface.co/models';
const MODEL_NAME = 'gpt2';

async function generateArticle() {
	try {
		const apiKey = process.env.HUGGINGFACE_API_KEY;

		if (!apiKey) {
			console.warn('HUGGINGFACE_API_KEY not set, using fallback content');
			return generateFallbackArticle();
		}

		const topics = [
			'Ancient Egypt and the pyramids',
			'The Roman Empire',
			'The Renaissance period',
			'World War I',
			'World War II',
			'The Cold War',
			'Ancient Greece and democracy',
			'The Middle Ages',
			'The Industrial Revolution',
			'The Age of Exploration',
			'The French Revolution',
			'The American Civil War',
			'The Byzantine Empire',
			'Ancient China and the Silk Road',
			'The Vikings',
			'The Ottoman Empire',
			'The Aztec civilization',
			'The Inca Empire',
			'The Mongol Empire',
			'Ancient Mesopotamia',
		];

		const topic = topics[Math.floor(Math.random() * topics.length)];
		const prompt = `Write a blog post about the history of ${topic}. Title: `;

		const response = await axios.post(
			`${HUGGINGFACE_API_URL}/${MODEL_NAME}`,
			{
				inputs: prompt,
				parameters: {
					max_length: 500,
					temperature: 0.9,
					do_sample: true,
				},
			},
			{
				headers: {
					Authorization: `Bearer ${apiKey}`,
					'Content-Type': 'application/json',
				},
				timeout: 30000,
			}
		);

		let generatedText = response.data[0]?.generated_text || '';

		if (generatedText.startsWith(prompt)) {
			generatedText = generatedText.substring(prompt.length).trim();
		}

		generatedText = cleanMarkdownHeaders(generatedText);

		const lines = generatedText.split('\n').filter((line) => line.trim());
		let title = lines[0] || `The History of ${topic}`;
		title = title.substring(0, 100).trim();

		let content = generatedText;
		if (lines.length > 0 && content.startsWith(lines[0])) {
			content = content.substring(lines[0].length).trim();
		}
		content =
			content || `This article explores the fascinating history of ${topic}...`;

		return {
			title: title || `The History of ${topic}`,
			content: content.substring(0, 5000),
		};
	} catch (error) {
		console.error('Error generating article with AI:', error.message);
		return generateFallbackArticle();
	}
}

function cleanMarkdownHeaders(text) {
	if (!text) return text;

	text = text.replace(/^#+\s+/gm, '');

	text = text.replace(/\n{3,}/g, '\n\n');

	text = text.replace(/^[\*\-\+]\s+/gm, '');

	text = text.replace(/^\*\*/gm, '').replace(/\*\*$/gm, '');

	return text.trim();
}

function generateFallbackArticle() {
	const topics = [
		'Ancient Egypt and the Pyramids',
		'The Roman Empire',
		'The Renaissance Period',
		'World War I',
		'World War II',
		'The Cold War',
		'Ancient Greece and Democracy',
		'The Middle Ages',
		'The Industrial Revolution',
		'The Age of Exploration',
		'The French Revolution',
		'The American Civil War',
		'The Byzantine Empire',
		'Ancient China and the Silk Road',
		'The Vikings',
		'The Ottoman Empire',
		'The Aztec Civilization',
		'The Inca Empire',
		'The Mongol Empire',
		'Ancient Mesopotamia',
	];

	const topic = topics[Math.floor(Math.random() * topics.length)];

	return {
		title: `The History of ${topic}`,
		content: `


Introduction

${topic} represents one of the most fascinating periods in human history. This article explores the key events, figures, and impacts that shaped this era and continue to influence our world today.

Historical Background

The story of ${topic} begins centuries ago and reflects the complex interactions of politics, culture, economics, and human ambition. Understanding the context of this period helps us appreciate its significance in the broader narrative of world history.

Key Events and Developments

Throughout this period, numerous pivotal events occurred that would reshape the course of history. From major battles and revolutions to cultural movements and technological advances, these developments created lasting changes that echo through time.

Important Figures

Many notable individuals played crucial roles during this era. Their decisions, innovations, and leadership helped shape the course of events and left indelible marks on history.

Impact on Modern World

The legacy of ${topic} extends far beyond its own time. The institutions, ideas, and conflicts of this period continue to influence global politics, culture, and society in profound ways.

Conclusion

Studying the history of ${topic} provides valuable insights into how societies evolve, how civilizations rise and fall, and how the past continues to inform our present. Understanding these historical lessons helps us navigate the challenges of today and shape a better future.

This article was auto-generated by AI as part of a historical blog demonstration.
    `.trim(),
	};
}

module.exports = {
	generateArticle,
};
